package vista;

import datos.AlmacenamientoColab;
import datos.AlmacenamientoProyectos;
import datos.AlmacenamientoTareas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.TareasDeProyecto;

/**
 * Dialogo de gestion de tareas
 * @author galfa
 */
public class DlgGestionTareas extends javax.swing.JDialog {

    protected AlmacenamientoTareas listaTareas;
    protected AlmacenamientoColab listaColab;
    protected AlmacenamientoProyectos listaProyectos;
    protected DefaultTableModel tblModel;

    /**
     * Constructor del dialogo sin datos iniciales
     * @param parent ventana principal
     * @param modal indica si el dialogo es modal
     */
    public DlgGestionTareas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Constructor del dialogo con listas
     * @param parent ventana principal
     * @param modal indica si el dialogo es modal
     * @param listaTareas almacenamiento de tareas
     * @param listaColab almacenamiento de colaboradores
     * @param listaProyectos almacenamiento de proyectos
     */
    public DlgGestionTareas(java.awt.Frame parent, boolean modal, AlmacenamientoTareas listaTareas, AlmacenamientoColab listaColab, AlmacenamientoProyectos listaProyectos) {
        super(parent, modal);
        initComponents();
        this.listaTareas = listaTareas;
        this.listaColab = listaColab;
        this.listaProyectos = listaProyectos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTareas = new javax.swing.JTable();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insert.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTareas);

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de registros:");

        txtCant.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Abre el dialogo para insertar una tarea
     * @param evt evento de accion generado por el boton insertar
     */
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNuevaTarea win = new DlgNuevaTarea(null, true, listaTareas, listaColab, listaProyectos);
        win.setLocationRelativeTo(this);
        win.setVisible(true);
        muestraTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed
    /**
     * Se ejecuta al activar la ventana 
     * @param evt evento de activacion de ventana
     */

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated
    /**
     * Elimina la tarea seleccionado en la tabla si existe
     * @param evt evento de accion generado por el boton eliminar
     */

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblTareas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 tarea");
            return;
        }
        int id = Integer.parseInt(tblTareas.getValueAt(fila, 0).toString());
        int r = JOptionPane.showConfirmDialog(this, "Eliminar tarea " + id + " ?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            boolean ok = listaTareas.eliminar(id);
            if (!ok) {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar");
            }
            muestraTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Abre el dialogo para editar la tarea seleccionado 
     * @param evt evento de accion generado por el boton editar
     */

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblTareas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 tarea");
            return;
        }
        int id = Integer.parseInt(tblTareas.getValueAt(fila, 0).toString());
        TareasDeProyecto t = listaTareas.buscar(id);
        if (t == null) {
            JOptionPane.showMessageDialog(this, "No se encontro la tarea seleccionada");
            return;
        }
        DlgNuevaTarea win = new DlgNuevaTarea(null, true, listaTareas, listaColab, listaProyectos, t);
        win.setTitle("Editar Tarea");
        win.setLocationRelativeTo(this);
        win.setVisible(true);
        muestraTabla();
    }//GEN-LAST:event_btnEditarActionPerformed
    
    /**
     * Filtra las tareas
     * @param evt evento de tecla liberada en el campo de texto
     */ 
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String titulo[] = {"ID", "Nombre", "Proyecto", "Colaborador",
            "Inicio", "Fin", "Duracion", "Estado", "Avance %"};

        tblModel = new DefaultTableModel(null, titulo);

        String filtro = txtBuscar.getText().toLowerCase();

        for (TareasDeProyecto tarea : listaTareas.mostrar()) {

            String idComoTexto = String.valueOf(tarea.getIdTarea());
            String nombreTarea = tarea.getNomTarea();

            String nombreProyecto = listaProyectos.nombrePorId(tarea.getIdProyecto());
            String nombreColaborador = listaColab.nombrePorId(tarea.getIdColaborador());

            boolean coincide = false;

            if (idComoTexto.contains(filtro)) {
                coincide = true;
            }
            if (!coincide) {
                if (nombreTarea != null) {
                    String nombreTareaLower = nombreTarea.toLowerCase();
                    if (nombreTareaLower.contains(filtro)) {
                        coincide = true;
                    }
                }
            }
            if (!coincide) {
                if (nombreProyecto != null) {
                    String nombreProyectoLower = nombreProyecto.toLowerCase();
                    if (nombreProyectoLower.contains(filtro)) {
                        coincide = true;
                    }
                }
            }
            if (!coincide) {
                if (nombreColaborador != null) {
                    String nombreColaboradorLower = nombreColaborador.toLowerCase();
                    if (nombreColaboradorLower.contains(filtro)) {
                        coincide = true;
                    }
                }
            }

            if (coincide) {
                String proyectoMostrar = "";
                if (nombreProyecto != null) {
                    proyectoMostrar = nombreProyecto;
                }

                String colaboradorMostrar = "";
                if (nombreColaborador != null) {
                    colaboradorMostrar = nombreColaborador;
                }

                String estadoMostrar = "";
                if (tarea.getEstado() != null) {
                    estadoMostrar = tarea.getEstado().name();
                }

                Object row[] = {
                    tarea.getIdTarea(),
                    nombreTarea,
                    proyectoMostrar,
                    colaboradorMostrar,
                    tarea.getFechInicio(),
                    tarea.getFechFin(),
                    tarea.getDuracion(),
                    estadoMostrar,
                    tarea.getPorcAvance()
                };
                tblModel.addRow(row);
            }
        }

        tblTareas.setModel(tblModel);
        txtCant.setText(String.valueOf(tblTareas.getRowCount()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * Carga todos los colaboradores en la tabla sin aplicar filtros 
     * 
     */
    private void muestraTabla() {
        String[] titulo = {
            "ID", "Nombre", "Proyecto", "Colaborador",
            "Inicio", "Fin", "Duracion", "Estado", "Avance %"
        };

        DefaultTableModel model = new DefaultTableModel(null, titulo);
        if (listaTareas == null || listaProyectos == null || listaColab == null) {
            tblTareas.setModel(model);
            txtCant.setText("0");
            return;
        }

        for (TareasDeProyecto tarea : listaTareas.mostrar()) {

            String nombreProyecto = listaProyectos.nombrePorId(tarea.getIdProyecto());
            if (nombreProyecto == null) {
                nombreProyecto = "";
            }

            String nombreColaborador = listaColab.nombrePorId(tarea.getIdColaborador());
            if (nombreColaborador == null) {
                nombreColaborador = "";
            }

            String estadoMostrar = "";
            if (tarea.getEstado() != null) {
                estadoMostrar = tarea.getEstado().name();
            }

            Object[] row = {
                tarea.getIdTarea(),
                tarea.getNomTarea(),
                nombreProyecto,
                nombreColaborador,
                tarea.getFechInicio(),
                tarea.getFechFin(),
                tarea.getDuracion(),
                estadoMostrar,
                tarea.getPorcAvance()
            };
            model.addRow(row);
        }

        tblTareas.setModel(model);
        txtCant.setText(Integer.toString(model.getRowCount()));
    }

    /**
     * Metodo principal que inicia el dialogo de gestion de colaboradores
     *
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgGestionTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgGestionTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgGestionTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgGestionTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgGestionTareas dialog = new DlgGestionTareas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblTareas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
