package vista;

import datos.AlmacenamientoProyectos;
import datos.AlmacenamientoTareas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Proyectos;
import logica.TareasDeProyecto;
/**
 * Dialogo de gestion de proyectos Permite visualizar, editar y administrar
 * los datos de los proyectos
 * @author Andres, Gerald, Kristy
 */

public class DlgGestionProyectos extends javax.swing.JDialog {

    protected AlmacenamientoProyectos listaProyectos;
    protected AlmacenamientoTareas listaTareas;
    protected DefaultTableModel tblModel;

    /**
     * Constructor por defecto 
     * @param parent
     * @param modal
     */
    public DlgGestionProyectos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.listaProyectos = new AlmacenamientoProyectos();
        this.listaTareas = new AlmacenamientoTareas();
    }

    /**
     * Constructor completo
     */
    public DlgGestionProyectos(java.awt.Frame parent, boolean modal, AlmacenamientoProyectos listaProyectos, AlmacenamientoTareas listaTareas) {
        super(parent, modal);
        initComponents();
        this.listaProyectos = listaProyectos;
        this.listaTareas = listaTareas;
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProyectos = new javax.swing.JTable();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setText("Buscar:");
        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insert.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProyectos);

        lblCant.setText("Cantidad de Proyectos");
        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtCant.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 541, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Abre el dialogo para insertar un nuevo colaborador
     * @param evt evento de accion generado por el boton insertar
     */

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNuevoProyecto win = new DlgNuevoProyecto(null, true, this.listaProyectos);
        win.setLocationRelativeTo(this);
        win.setVisible(true);
        muestraTabla();
    }//GEN-LAST:event_btnInsertarActionPerformed
    /**
     * Se ejecuta al activar la ventana
     * @param evt evento de activacion de ventana
     */

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated
    /**
     * Elimina el proyecto seleccionado en la tabla si existe 
     * confirmacion antes de eliminar y muestra mensajes segun el resultado
     * @param evt evento de accion generado por el boton eliminar
     */

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblProyectos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 proyecto");
            return;
        }
        int id = Integer.parseInt(tblProyectos.getValueAt(fila, 0).toString());
        int r = JOptionPane.showConfirmDialog(this, "Eliminar proyecto " + id + " ?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            boolean ok = listaProyectos.eliminar(id);
            if (!ok) {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar");
            }
            muestraTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    /**
     * Abre el dialogo para editar el colaborador seleccionado
     * del colaborador y actualiza la lista si se modifico
     * @param evt evento de accion generado por el boton editar
     */

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tblProyectos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 proyecto");
            return;
        }
        int id = Integer.parseInt(tblProyectos.getValueAt(fila, 0).toString());
        Proyectos seleccionado = listaProyectos.buscar(id);
        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el proyecto seleccionado");
            return;
        }
        DlgNuevoProyecto win = new DlgNuevoProyecto(null, true, this.listaProyectos, seleccionado);
        win.setLocationRelativeTo(this);
        win.setVisible(true);
        muestraTabla();
    }//GEN-LAST:event_btnEditarActionPerformed
    /**
     * Filtra los colaboradores segun el texto ingresado 
     * Actualiza la tabla mostrando solo los que coinciden por cedula, nombre o
     * puesto
     * @param evt evento de tecla liberada en el campo de texto
     */

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String[] titulo = {"ID", "Nombre", "Fecha Inicio", "Fecha Fin", "Duracion", "Estado", "Avance"};
        tblModel = new DefaultTableModel(null, titulo);

        String filtro = txtBuscar.getText();
        if (filtro == null) {
            filtro = "";
        }
        filtro = filtro.toLowerCase();

        if (listaProyectos == null) {
            tblProyectos.setModel(tblModel);
            txtCant.setText("0");
            return;
        }

        for (Proyectos proyecto : listaProyectos.mostrar()) {
            boolean coincide = false;

            String idComoTexto = String.valueOf(proyecto.getIdProyecto());
            if (idComoTexto.toLowerCase().contains(filtro)) {
                coincide = true;
            }
            if (!coincide) {
                String nombreProyecto = proyecto.getNomProyecto();
                if (nombreProyecto != null && nombreProyecto.toLowerCase().contains(filtro)) {
                    coincide = true;
                }
            }
            if (!coincide) {
                String estadoProyecto = proyecto.getEstado();
                if (estadoProyecto != null && estadoProyecto.toLowerCase().contains(filtro)) {
                    coincide = true;
                }
            }

            if (coincide) {
                int avanceMostrado = 0;
                if (listaTareas != null) {
                    java.util.ArrayList<TareasDeProyecto> tareas = listaTareas.listarPorProyecto(proyecto.getIdProyecto());
                    avanceMostrado = proyecto.calcAvance(tareas); 
                }

                Object[] row = {
                    proyecto.getIdProyecto(),
                    proyecto.getNomProyecto(),
                    proyecto.getFechInicio(),
                    proyecto.getFechFin(),
                    proyecto.getDuracionDias(),
                    proyecto.getEstado(),
                    avanceMostrado
                };
                tblModel.addRow(row);
            }
        }

        tblProyectos.setModel(tblModel);
        txtCant.setText(String.valueOf((char) tblProyectos.getRowCount()));
    }//GEN-LAST:event_txtBuscarKeyReleased


    /**
     * Carga todos los proyectos en la tabla
     */
    private void muestraTabla() {
        String[] titulo = {"ID", "Nombre", "Fecha Inicio", "Fecha Fin", "Duracion", "Estado", "Avance"};
        tblModel = new DefaultTableModel(null, titulo);

        if (listaProyectos == null) {
            tblProyectos.setModel(tblModel);
            txtCant.setText("0");
            return;
        }

        for (Proyectos proyecto : listaProyectos.mostrar()) {
            int avanceMostrado = 0;
            if (listaTareas != null) {
                java.util.ArrayList<TareasDeProyecto> tareas
                        = listaTareas.listarPorProyecto(proyecto.getIdProyecto());
                avanceMostrado = proyecto.calcAvance(tareas); 
            }

            Object[] row = {
                proyecto.getIdProyecto(),
                proyecto.getNomProyecto(),
                proyecto.getFechInicio(),
                proyecto.getFechFin(),
                proyecto.getDuracionDias(),
                proyecto.getEstado(), 
                avanceMostrado 
            };
            tblModel.addRow(row);
        }

        tblProyectos.setModel(tblModel);
        txtCant.setText(String.valueOf(tblProyectos.getRowCount()));
    }

    
    /**
     * Metodo principal que inicia el dialogo de gestion de colaboradores
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            DlgGestionProyectos dialog = new DlgGestionProyectos(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblProyectos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
