
package vista;




import datos.AlmacenamientoProyectos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Colaborador;
import logica.Proyectos;

import vista.DlgNuevoProyecto;

/**
 * Dialogo de gestion de colaboradores Permite visualizar, editar y administrar
 * los datos de los colaboradores registrados Utiliza instancias de
 * AlmacenamientoColab y AlmacenamientoPuestos para operar sobre los datos
 *
 * @author Andres
 */

public class DlgGestionProyectos extends javax.swing.JDialog {

    protected AlmacenamientoProyectos listaProyectos;
    private DefaultTableModel tblModel;

   
    /**
     * Crea una nueva instancia del dialogo sin listas de datos
     *
     * @param parent ventana padre
     * @param modal indica si el dialogo es modal
     */
    public DlgGestionProyectos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    
    public DlgGestionProyectos(java.awt.Frame parent, boolean modal, AlmacenamientoProyectos listaProyectos) {
        super(parent, modal);
        initComponents();
        this.listaProyectos = listaProyectos;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProyecto = new javax.swing.JTable();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insert.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProyecto);

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de Proyectos");

        txtCant.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Abre el dialogo para insertar un nuevo colaborador Actualiza la lista de
     * colaboradores si se agrego uno nuevo
     *
     * @param evt evento de accion generado por el boton insertar
     */

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNuevoProyecto win = new DlgNuevoProyecto(null, true, listaProyectos);
        win.setTitle("Agregar un nuevo Proyecto");
        win.setLocationRelativeTo(null);
        win.setVisible(true);
        this.listaProyectos = win.listaProyectos;
    }//GEN-LAST:event_btnInsertarActionPerformed
    /**
     * Se ejecuta al activar la ventana Refresca la tabla de colaboradores
     * mostrados
     *
     * @param evt evento de activacion de ventana
     */

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        mostrarTablaProyectos();
    }//GEN-LAST:event_formWindowActivated
    /**
     * Elimina el proyecto seleccionado en la tabla si existe Solicita
     * confirmacion antes de eliminar y muestra mensajes segun el resultado
     *
     * @param evt evento de accion generado por el boton eliminar
     */

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblProyecto.getSelectedRowCount() == 1) {
            int fila = tblProyecto.getSelectedRow();
            int id = listaProyectos.getListaProyectos().get(fila).getIdProyecto();

            int resp = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el proyecto?");
            if (resp == JOptionPane.YES_OPTION) {
                if (listaProyectos.eliminar(id)) {
                    JOptionPane.showMessageDialog(this, "Proyecto eliminado");
                    // Aquí podrías actualizar la tabla para reflejar el cambio
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el proyecto");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un solo proyecto");
        }
    }

    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Abre el dialogo para editar el colaborador seleccionado Carga los datos
     * del colaborador y actualiza la lista si se modifico
     *
     * @param evt evento de accion generado por el boton editar
     */

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
//        if (tblProyecto.getSelectedRowCount() == 1) {
//        int fila = tblProyecto.getSelectedRow();
//        Proyectos proyectoOriginal = listaProyectos.getListaProyectos().get(fila);
//
//        // Obtener el nuevo nombre desde el campo de texto
//        String nuevoNombre = txtId.getText().trim();
//
//        // Validar que el nombre no esté vacío
//        if (nuevoNombre.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío");
//            return;
//        }
//
//        // Crear el proyecto modificado con el mismo ID y nuevo nombre
//        Proyectos proyectoModificado = new Proyectos();
//        proyectoModificado.setIdProyecto(proyectoOriginal.getIdProyecto());
//        proyectoModificado.setNombre(nuevoNombre);
//
//        // Intentar modificar en el almacenamiento
//        if (listaProyectos.modificar(proyectoModificado)) {
//            JOptionPane.showMessageDialog(this, "Proyecto modificado correctamente");
//            
//        } else {
//            JOptionPane.showMessageDialog(this, "No se pudo modificar el proyecto");
//        }
//    } else {
//        JOptionPane.showMessageDialog(this, "Debe seleccionar un solo proyecto para editar");
//    }

    }//GEN-LAST:event_btnEditarActionPerformed
    /**
     * Filtra los colaboradores segun el texto ingresado en el campo de busqueda
     * Actualiza la tabla mostrando solo los que coinciden por cedula, nombre o
     * puesto
     *
     * @param evt evento de tecla liberada en el campo de texto
     */

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
//         try {
//        int idBuscado = Integer.parseInt(txtIdBuscar.getText().trim());
//
//        Proyectos proyectoEncontrado = listaProyectos.buscar(idBuscado);
//
//        if (proyectoEncontrado != null) {
//            txtNombre.setText(proyectoEncontrado.getNombre());
//            JOptionPane.showMessageDialog(this, "Proyecto encontrado");
//        } else {
//            JOptionPane.showMessageDialog(this, "No se encontró ningún proyecto con ese ID");
//            txtNombre.setText("");
//        }
//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(this, "El ID debe ser un número entero");
//    }
//}

    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * Detecta doble clic sobre la tabla cuando se esta seleccionando un jefe
     * Asigna la cedula y nombre del jefe seleccionado y cierra el dialogo
     *
     * @param evt evento de clic del mouse sobre la tabla
     */
   

        
}
}

    /**
     * Carga todos los colaboradores en la tabla sin aplicar filtros Muestra la
     * cantidad total en el campo correspondiente
     */
//    public void mostrarTablaProyectos() {
//    DefaultTableModel modelo = (DefaultTableModel) tblProyecto.getModel();
//    modelo.setRowCount(0); // Limpiar la tabla
//
//    for (Proyectos p : listaProyectos.mostrar()) {
//        Object[] fila = { p.getIdProyecto(), p.getNombre() };
//        modelo.addRow(fila);
//    }
}
    /**
     * Metodo principal que inicia el dialogo de gestion de colaboradores
     * Configura el estilo visual y lanza la ventana en el hilo de eventos
     *
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(DlgGestionProyectos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            DlgGestionProyectos dialog = new DlgGestionProyectos(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblProyecto;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
