package vista;

import datos.AlmacenamientoColab;
import datos.AlmacenamientoPuestos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Colaborador;

/**
 * Dialogo de gestion de colaboradores Permite visualizar, editar y administrar
 * los datos de los colaboradores registrados Utiliza instancias de
 * AlmacenamientoColab y AlmacenamientoPuestos para operar sobre los datos
 *
 * @author Andres
 */
public class DlgGestionColaboradores extends javax.swing.JDialog {

    protected AlmacenamientoColab listaColab;
    protected AlmacenamientoPuestos listaPuestos;
    private DefaultTableModel tblModel;

    protected int cedJefe;
    protected String nombreJefe;

    /**
     * Crea una nueva instancia del dialogo sin listas de datos
     *
     * @param parent ventana padre
     * @param modal indica si el dialogo es modal
     */
    public DlgGestionColaboradores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Crea una nueva instancia del dialogo con listas de colaboradores y
     * puestos
     *
     * @param parent ventana padre
     * @param modal indica si el dialogo es modal
     * @param listaColab instancia de almacenamiento de colaboradores
     * @param listaPuestos instancia de almacenamiento de puestos
     */
    public DlgGestionColaboradores(java.awt.Frame parent, boolean modal, AlmacenamientoColab listaColab, AlmacenamientoPuestos listaPuestos) {
        super(parent, modal);
        initComponents();
        this.listaColab = listaColab;
        this.listaPuestos = listaPuestos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblColab = new javax.swing.JTable();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBuscar.setText("Buscar:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/insert.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tblColab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblColab);

        lblCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCant.setText("Cantidad de registros:");

        txtCant.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Abre el dialogo para insertar un nuevo colaborador Actualiza la lista de
     * colaboradores si se agrego uno nuevo
     *
     * @param evt evento de accion generado por el boton insertar
     */

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        DlgNuevoColaborador win = new DlgNuevoColaborador(null, true, listaColab, listaPuestos);
        win.setTitle("Agregar un nuevo Colaborador");
        win.setLocationRelativeTo(null);
        win.setVisible(true);
        this.listaColab = win.listaColab;
    }//GEN-LAST:event_btnInsertarActionPerformed
    /**
     * Se ejecuta al activar la ventana Refresca la tabla de colaboradores
     * mostrados
     *
     * @param evt evento de activacion de ventana
     */

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        muestraTabla();
    }//GEN-LAST:event_formWindowActivated
    /**
     * Elimina el colaborador seleccionado en la tabla si existe Solicita
     * confirmacion antes de eliminar y muestra mensajes segun el resultado
     *
     * @param evt evento de accion generado por el boton eliminar
     */

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblColab.getSelectedRowCount() == 1) {
            int ced = listaColab.getArrayColab().get(tblColab.getSelectedRow()).getCedula();
            int resp = JOptionPane.showConfirmDialog(this, "Quiere eliminar el Colaborador?");
            //System.out.println(resp);
            if (resp == 0) {  //Sí quiere eliminar el auto
                if (listaColab.eliminarColab(listaColab.buscaCedula(ced))) {
                    JOptionPane.showMessageDialog(this, "Colaborador eliminado");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 Colaborador");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    /**
     * Abre el dialogo para editar el colaborador seleccionado Carga los datos
     * del colaborador y actualiza la lista si se modifico
     *
     * @param evt evento de accion generado por el boton editar
     */

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblColab.getSelectedRowCount() == 1) {
            int pos = tblColab.getSelectedRow();
            int ced = listaColab.getArrayColab().get(tblColab.getSelectedRow()).getCedula();

            Colaborador colab = listaColab.buscaCedula(ced);

            DlgNuevoColaborador winEditar = new DlgNuevoColaborador(null, true, listaColab, colab, pos, listaPuestos);

            winEditar.setTitle("Editar Colabprador");
            winEditar.setLocationRelativeTo(null);
            winEditar.setVisible(true);

            this.listaColab = winEditar.listaColab;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar 1 Colaborador");
        }
    }//GEN-LAST:event_btnEditarActionPerformed
    /**
     * Filtra los colaboradores segun el texto ingresado en el campo de busqueda
     * Actualiza la tabla mostrando solo los que coinciden por cedula, nombre o
     * puesto
     *
     * @param evt evento de tecla liberada en el campo de texto
     */

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String titulo[] = {"Cédula", "Nombre", "Teléfono", "Email",
            "Dirección", "Puesto", "Fecha Nac", "Fecha Ingreso",
            "Fecha Despido", "Jefe"};

        Colaborador colab;

        tblModel = new DefaultTableModel(null, titulo);

        for (int i = 0; i < listaColab.getArrayColab().size(); i++) {
            colab = listaColab.getArrayColab().get(i);

            if (String.valueOf(colab.getCedula()).contains(txtBuscar.getText())
                    || colab.getNombre().toLowerCase().contains(txtBuscar.getText().toLowerCase())
                    || colab.getPuesto().getNomPuesto().contains(txtBuscar.getText().toLowerCase())) {
                String puesto = listaColab.getArrayColab().get(i).
                        getPuesto().getNomPuesto();
                Object row[] = {listaColab.getArrayColab().get(i).getCedula(),
                    listaColab.getArrayColab().get(i).getNombre(),
                    listaColab.getArrayColab().get(i).getTelefono(),
                    listaColab.getArrayColab().get(i).getEmail(),
                    listaColab.getArrayColab().get(i).getDireccion(),
                    puesto,
                    listaColab.getArrayColab().get(i).getFechaNac(),
                    listaColab.getArrayColab().get(i).getFechIngreso()};

                tblModel.addRow(row);
            }
        }

        tblColab.setModel(tblModel);
        txtCant.setText(String.valueOf(tblColab.getRowCount()));
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * Detecta doble clic sobre la tabla cuando se esta seleccionando un jefe
     * Asigna la cedula y nombre del jefe seleccionado y cierra el dialogo
     *
     * @param evt evento de clic del mouse sobre la tabla
     */
    private void tblColabMousePressed(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2 && this.getTitle().equals("Seleccione el Jefe")) {
            this.cedJefe = Integer.parseInt(tblColab.getValueAt(tblColab.getSelectedRow(), 0).toString());

            this.nombreJefe = tblColab.getValueAt(tblColab.getSelectedRow(), 1).toString();

            this.dispose();
        }
    }

    /**
     * Carga todos los colaboradores en la tabla sin aplicar filtros Muestra la
     * cantidad total en el campo correspondiente
     */
    private void muestraTabla() {
        String titulo[] = {"Cédula", "Nombre", "Teléfono", "Email",
            "Dirección", "Puesto", "Fecha Nac", "Fecha Ingreso",
            "Fecha Despido", "Jefe"};

        tblModel = new DefaultTableModel(null, titulo);
        for (int i = 0; i < listaColab.getArrayColab().size(); i++) {
            String puesto = listaColab.getArrayColab().get(i).
                    getPuesto().getNomPuesto();
            Object row[] = {listaColab.getArrayColab().get(i).getCedula(),
                listaColab.getArrayColab().get(i).getNombre(),
                listaColab.getArrayColab().get(i).getTelefono(),
                listaColab.getArrayColab().get(i).getEmail(),
                listaColab.getArrayColab().get(i).getDireccion(),
                puesto,
                listaColab.getArrayColab().get(i).getFechaNac(),
                listaColab.getArrayColab().get(i).getFechIngreso()};

            tblModel.addRow(row);
        }

        tblColab.setModel(tblModel);
        txtCant.setText(String.valueOf(tblColab.getRowCount()));
    }

    /**
     * Metodo principal que inicia el dialogo de gestion de colaboradores
     * Configura el estilo visual y lanza la ventana en el hilo de eventos
     *
     * @param args argumentos de linea de comandos
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgGestionColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgGestionColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgGestionColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgGestionColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgGestionColaboradores dialog = new DlgGestionColaboradores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JTable tblColab;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCant;
    // End of variables declaration//GEN-END:variables
}
