package vista;

import datos.AlmacenamientoColab;
import datos.AlmacenamientoProyectos;
import datos.AlmacenamientoTareas;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import logica.Colaborador;
import logica.EstadoTarea;
import logica.Proyectos;
import logica.TareasDeProyecto;

/**
 * Dialogo para crear y editar tareas
 * @author galfa
 */
public class DlgNuevaTarea extends javax.swing.JDialog {
    
    protected AlmacenamientoTareas listaTareas;
    protected AlmacenamientoColab listaColab;
    protected AlmacenamientoProyectos listaProyectos;
    protected TareasDeProyecto tareaEdicion;

    /**
     * Constructor del dialogo sin datos iniciales
     * @param parent ventana principal
     * @param modal indica si el dialogo es modal
     */
    public DlgNuevaTarea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Constructor del dialogo con listas
     * @param parent ventana principal
     * @param modal indica si el dialogo es modal
     * @param listaTareas almacenamiento de tareas
     * @param listaColab almacenamiento de colaboradores
     * @param listaPuestos almacenamiento de puestos
     */
    public DlgNuevaTarea(java.awt.Frame parent, boolean modal, AlmacenamientoTareas listaTareas, AlmacenamientoColab listaColab, AlmacenamientoProyectos listaProyectos) {
        super(parent, modal);
        initComponents();
        this.listaTareas = listaTareas;
        this.listaColab = listaColab;
        this.listaProyectos = listaProyectos;
        this.tareaEdicion = null;
    }

    /**
     * Constructor del dialogo con listas
     * @param parent ventana principal
     * @param modal indica si el dialogo es modal
     * @param listaTareas almacenamiento de tareas
     * @param listaColab almacenamiento de colaboradores
     * @param listaPuestos almacenamiento de puestos
     * @param tareaEditar tarea que se edita
     */
    public DlgNuevaTarea(java.awt.Frame parent, boolean modal, AlmacenamientoTareas listaTareas, AlmacenamientoColab listaColab, AlmacenamientoProyectos listaProyectos, TareasDeProyecto tareaEditar) {
        super(parent, modal);
        initComponents();
        this.listaTareas = listaTareas;
        this.listaColab = listaColab;
        this.listaProyectos = listaProyectos;
        this.tareaEdicion = tareaEditar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblProyecto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblColab = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        lblDur = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbColab = new javax.swing.JComboBox();
        dtpInicio = new com.github.lgooddatepicker.components.DatePicker();
        dtpFin = new com.github.lgooddatepicker.components.DatePicker();
        jLabel3 = new javax.swing.JLabel();
        txtAvance = new javax.swing.JTextField();
        cmbProyecto = new javax.swing.JComboBox();
        cmbEstado = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Nueva Tarea");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblId.setText("ID");
        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNombre.setText("Nombre");
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblProyecto.setText("Proyecto");
        lblProyecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setText("Inicio");

        jLabel2.setText("Fin");

        lblColab.setText("Colaborador");

        txtDuracion.setEditable(false);
        txtDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDur.setText("Duracion");

        lblEstado.setText("Estado");

        cmbColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColabActionPerformed(evt);
            }
        });

        jLabel3.setText("Avance");

        txtAvance.setEditable(false);

        cmbProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProyectoActionPerformed(evt);
            }
        });

        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombre)
                            .addComponent(lblId)
                            .addComponent(lblProyecto))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(lblDur)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstado)
                            .addComponent(lblColab)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbColab, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(153, 153, 153)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dtpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dtpFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dtpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dtpFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDur)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProyecto)
                            .addComponent(cmbProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColab)
                            .addComponent(cmbColab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnGuardar)
                .addGap(65, 65, 65)
                .addComponent(btnCancelar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inserta una tarea nueva al igual que tiene una serie de 
     * confirmaciones antes de poder insertar una tarea nueva
     * para validad IDs unicos
     * 
     * @param evt evento de boton guardar
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // validacion de campos
        if (txtId.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Debe indicar el ID");
            return;
        }
        if (txtNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Debe indicar el nombre de la tarea");
            return;
        }
        if (cmbProyecto.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proyecto");
            return;
        }
        if (cmbColab.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un colaborador");
            return;
        }
        if (dtpInicio.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe indicar la fecha de inicio");
            return;
        }
        if (dtpFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe indicar la fecha de fin");
            return;
        }
        if (cmbEstado.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el estado");
            return;
        }

        try {
            int idTarea = Integer.parseInt(txtId.getText().trim());
            String nombre = txtNombre.getText().trim();

            Proyectos proyectoSeleccionado = (Proyectos) cmbProyecto.getSelectedItem();
            Colaborador colaboradorSeleccionado = (Colaborador) cmbColab.getSelectedItem();
            EstadoTarea estadoSeleccionado = (EstadoTarea) cmbEstado.getSelectedItem();

            if (proyectoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Proyecto invalido");
                return;
            }
            if (colaboradorSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Colaborador invalido");
                return;
            }
            if (estadoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "Estado invalido");
                return;
            }

            LocalDate fechaIni = dtpInicio.getDate();
            LocalDate fechaFin = dtpFin.getDate();
            if (fechaFin.isBefore(fechaIni)) {
                JOptionPane.showMessageDialog(this, "La fecha fin no puede ser anterior al inicio");
                return;
            }

            int duracion = (int) ChronoUnit.DAYS.between(fechaIni, fechaFin) + 1;

            // construir tarea nueva
            TareasDeProyecto tarea = new TareasDeProyecto();
            tarea.setIdTarea(idTarea);
            tarea.setNomTarea(nombre);
            tarea.setIdProyecto(proyectoSeleccionado.getIdProyecto());
            tarea.setIdColaborador(colaboradorSeleccionado.getIdColaborador());
            tarea.setFechInicio(fechaIni);
            tarea.setFechFin(fechaFin);
            tarea.setDuracion(duracion);
            tarea.setEstado(estadoSeleccionado);

            txtDuracion.setText(String.valueOf(duracion));
            txtAvance.setText(String.valueOf(tarea.getPorcAvance()));

            // reglas de validacion
            if (!tarea.verificarColaborador(tarea.getIdColaborador(), listaColab)) {
                JOptionPane.showMessageDialog(this, "El colaborador no existe");
                return;
            }
            if (!tarea.verificarProyecto(tarea.getIdProyecto(), listaProyectos)) {
                JOptionPane.showMessageDialog(this, "El proyecto no existe");
                return;
            }

            // guardar o editar la tarea
            boolean esEdicion = (tareaEdicion != null);
            if (!esEdicion) { // guardar
                boolean ok = listaTareas.insertar(tarea);
                if (!ok) {
                    JOptionPane.showMessageDialog(this, "El id de tarea ya existe");
                    return;
                }
                JOptionPane.showMessageDialog(this, "Tarea agregada con exito");
                this.dispose();
            } else { // editar
                boolean ok = listaTareas.modificar(tareaEdicion.getIdTarea(), tarea);
                if (!ok) {
                    JOptionPane.showMessageDialog(this, "No se pudo modificar la tarea");
                    return;
                }
                JOptionPane.showMessageDialog(this, "Tarea editada con exito");
                this.dispose();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID debe ser numerico");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * Inicializa combo y carga la ventana 
     * @param evt evento de ventana activada
     */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cargarCombos();

        if (tareaEdicion != null) {
            txtId.setText(String.valueOf(tareaEdicion.getIdTarea()));
            txtId.setEnabled(false);

            txtNombre.setText(tareaEdicion.getNomTarea());

            int posProy = listaProyectos.posicionPorId(tareaEdicion.getIdProyecto());
            if (posProy >= 0 && posProy < cmbProyecto.getItemCount()) {
                cmbProyecto.setSelectedIndex(posProy);
            }

            int posCol = listaColab.posicionPorId(tareaEdicion.getIdColaborador());
            if (posCol >= 0 && posCol < cmbColab.getItemCount()) {
                cmbColab.setSelectedIndex(posCol);
            }

            dtpInicio.setDate(tareaEdicion.getFechInicio());
            dtpFin.setDate(tareaEdicion.getFechFin());

            txtDuracion.setText(String.valueOf(tareaEdicion.getDuracion()));

            if (tareaEdicion.getEstado() != null) {
                cmbEstado.setSelectedItem(tareaEdicion.getEstado());
                txtAvance.setText(String.valueOf(tareaEdicion.getPorcAvance()));
            } else {
                txtAvance.setText("");
            }
        } else {
            txtId.setEnabled(true);
            txtId.requestFocus();
            txtDuracion.setText("");
            txtAvance.setText("");
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * Cierra el dialogo sin aplicar cambios
     * @param evt evento de boton cancelar
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbColabActionPerformed

    private void cmbProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProyectoActionPerformed
   
    /**
     * Con este metodo se traen los valores de EstadoTarea para que 
     * puedan aparecer en el combo de estado
     * @param evt combobox de EstadoTareas
     */
    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // cuando cambia el estado este muestra el avance que tiene que ser
        if (cmbEstado.getSelectedIndex() == -1) {
            txtAvance.setText("");
            return;
        }
        EstadoTarea estadoSeleccionado = (EstadoTarea) cmbEstado.getSelectedItem();
        if (estadoSeleccionado == null) {
            txtAvance.setText("");
            return;
        }
        TareasDeProyecto tareaTemp = new TareasDeProyecto();
        tareaTemp.setEstado(estadoSeleccionado);
        txtAvance.setText(String.valueOf(tareaTemp.getPorcAvance()));
    }//GEN-LAST:event_cmbEstadoActionPerformed

    /**
     * Este metodo hace que los combo que estan en el diseño
     * sean llenados por los valores que vienen desde las listas de
     * los diferentes almacenamiento, a los combo se les quito la propiedad
     * de String para que estos puedan funcionar
     */
    private void cargarCombos() {
        // Proyectos
        DefaultComboBoxModel<Proyectos> modeloProy = new DefaultComboBoxModel<Proyectos>();
        for (int i = 0; i < listaProyectos.mostrar().size(); i++) {
            Proyectos proyecto = listaProyectos.mostrar().get(i);
            modeloProy.addElement(proyecto);
        }
        cmbProyecto.setModel(modeloProy);

        // Colaboradores
        DefaultComboBoxModel<Colaborador> modeloCol = new DefaultComboBoxModel<Colaborador>();
        for (int j = 0; j < listaColab.getArrayColab().size(); j++) {
            Colaborador colaborador = listaColab.getArrayColab().get(j);
            modeloCol.addElement(colaborador); 
        }
        cmbColab.setModel(modeloCol);

        // Estados
        DefaultComboBoxModel<EstadoTarea> modeloEst = new DefaultComboBoxModel<EstadoTarea>(EstadoTarea.values());
        cmbEstado.setModel(modeloEst); 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgNuevaTarea dialog = new DlgNuevaTarea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbColab;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbProyecto;
    private com.github.lgooddatepicker.components.DatePicker dtpFin;
    private com.github.lgooddatepicker.components.DatePicker dtpInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblColab;
    private javax.swing.JLabel lblDur;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProyecto;
    private javax.swing.JTextField txtAvance;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
