/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import datos.AlmacenamientoColab;
import datos.AlmacenamientoProyectos;
import datos.AlmacenamientoPuestos;
import datos.AlmacenamientoTareas;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Andres, Gerald, Kristy
 */
public class FrmSistema extends javax.swing.JFrame {

    AlmacenamientoPuestos listaPuestos = new AlmacenamientoPuestos();
    AlmacenamientoColab listaColab = new AlmacenamientoColab();
    AlmacenamientoProyectos listaProyectos = new AlmacenamientoProyectos();
    AlmacenamientoTareas listaTareas = new AlmacenamientoTareas();
    
    /**
     * Creates new form SistemaPlanilla
     */
    public FrmSistema() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPuestos = new javax.swing.JButton();
        btnColabs = new javax.swing.JButton();
        btnProyectos = new javax.swing.JButton();
        btnGestionTareas = new javax.swing.JButton();
        btnEstadoProyecto = new javax.swing.JButton();
        btnEstadoTarea = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnModulos = new javax.swing.JMenu();
        itemPuestos = new javax.swing.JMenuItem();
        itemColab = new javax.swing.JMenuItem();
        itemGestionTareas = new javax.swing.JMenuItem();
        itemProyectos = new javax.swing.JMenuItem();
        itemAvanceTareas = new javax.swing.JMenuItem();
        itemEstadoProyectos = new javax.swing.JMenuItem();
        mnAcercade = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Planillas");
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPuestos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gestion de puestos.png"))); // NOI18N
        btnPuestos.setText("Gestión de Puestos");
        btnPuestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnPuestos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPuestos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuestosActionPerformed(evt);
            }
        });

        btnColabs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnColabs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion de colaboradores.png"))); // NOI18N
        btnColabs.setText("Gestión de Colaboradores");
        btnColabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnColabs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnColabs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnColabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColabsActionPerformed(evt);
            }
        });

        btnProyectos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gestion de proyectos.png"))); // NOI18N
        btnProyectos.setText("Gestión de Proyectos");
        btnProyectos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectosActionPerformed(evt);
            }
        });

        btnGestionTareas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGestionTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion de tareas.png"))); // NOI18N
        btnGestionTareas.setText("Gestión de Tareas");
        btnGestionTareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnGestionTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionTareasActionPerformed(evt);
            }
        });

        btnEstadoProyecto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEstadoProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avance y estado prpyecto.png"))); // NOI18N
        btnEstadoProyecto.setText("Avance  y Estado de Proyectos");
        btnEstadoProyecto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnEstadoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoProyectoActionPerformed(evt);
            }
        });

        btnEstadoTarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEstadoTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avance de tareas.png"))); // NOI18N
        btnEstadoTarea.setText("Avance  y Estado de Tareas");
        btnEstadoTarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnEstadoTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionTareas))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEstadoProyecto)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEstadoTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnColabs)
                            .addComponent(btnProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColabs, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstadoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstadoTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        mnModulos.setText("Modulos");

        itemPuestos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemPuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gestion de puestos.png"))); // NOI18N
        itemPuestos.setText("Gestion de Puestos");
        itemPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPuestosActionPerformed(evt);
            }
        });
        mnModulos.add(itemPuestos);

        itemColab.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemColab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion de colaboradores.png"))); // NOI18N
        itemColab.setText("Gestion de Colaboradores");
        itemColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemColabActionPerformed(evt);
            }
        });
        mnModulos.add(itemColab);

        itemGestionTareas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemGestionTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion de tareas.png"))); // NOI18N
        itemGestionTareas.setText("Gestion de Tareas");
        itemGestionTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionTareasActionPerformed(evt);
            }
        });
        mnModulos.add(itemGestionTareas);

        itemProyectos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gestion de proyectos.png"))); // NOI18N
        itemProyectos.setText("Gestion de Proyectos");
        itemProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProyectosActionPerformed(evt);
            }
        });
        mnModulos.add(itemProyectos);

        itemAvanceTareas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemAvanceTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avance de tareas.png"))); // NOI18N
        itemAvanceTareas.setText("Avance y Estado de Tareas");
        itemAvanceTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAvanceTareasActionPerformed(evt);
            }
        });
        mnModulos.add(itemAvanceTareas);

        itemEstadoProyectos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemEstadoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avance y estado prpyecto.png"))); // NOI18N
        itemEstadoProyectos.setText("Avance y Estado de Proyectos");
        itemEstadoProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEstadoProyectosActionPerformed(evt);
            }
        });
        mnModulos.add(itemEstadoProyectos);

        jMenuBar1.add(mnModulos);

        mnAcercade.setText("Acerca de");
        mnAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAcercadeActionPerformed(evt);
            }
        });

        itemAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        itemAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        itemAcerca.setText("Acerca de");
        itemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaActionPerformed(evt);
            }
        });
        mnAcercade.add(itemAcerca);

        jMenuBar1.add(mnAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPuestosActionPerformed
        btnPuestosActionPerformed(evt);
    }//GEN-LAST:event_itemPuestosActionPerformed

    private void btnPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuestosActionPerformed
        DlgGestionPuestos winPuestos = new DlgGestionPuestos(this, false, listaPuestos);
        winPuestos.setLocationRelativeTo(null);
        winPuestos.setTitle("Gestión de Puestos");
        winPuestos.setVisible(true);

        this.listaPuestos = winPuestos.listaPuestos;
    }//GEN-LAST:event_btnPuestosActionPerformed

    private void btnColabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColabsActionPerformed
        DlgGestionColaboradores winColab = new DlgGestionColaboradores(this, false, listaColab, listaPuestos);
        winColab.setLocationRelativeTo(null);
        winColab.setTitle("Gestión de Colaboradores");
        winColab.setVisible(true);
        
        this.listaColab = winColab.listaColab;
    }//GEN-LAST:event_btnColabsActionPerformed

    private void btnProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectosActionPerformed
        DlgGestionProyectos winProyectos = new DlgGestionProyectos(this, false, listaProyectos, listaTareas);
        winProyectos.setLocationRelativeTo(null);
        winProyectos.setTitle("Gestión de Proyectos");
        winProyectos.setVisible(true);
    }//GEN-LAST:event_btnProyectosActionPerformed

    private void btnGestionTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionTareasActionPerformed
        DlgGestionTareas winTareas = new DlgGestionTareas(this, false, listaTareas, listaColab, listaProyectos);
        winTareas.setLocationRelativeTo(null);
        winTareas.setTitle("Gestión de Tareas");
        winTareas.setVisible(true);

        this.listaTareas = winTareas.listaTareas;
    }//GEN-LAST:event_btnGestionTareasActionPerformed

    private void btnEstadoTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoTareaActionPerformed
        DlgAvanceTareas winAvance = new DlgAvanceTareas(this, false, listaTareas, listaColab, listaProyectos);
        winAvance.setTitle("Avance y Estado de Tareas");
        winAvance.setLocationRelativeTo(this);
        winAvance.setVisible(true);
    }//GEN-LAST:event_btnEstadoTareaActionPerformed

    private void btnEstadoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoProyectoActionPerformed
        DlgAvanceProyecto win = new DlgAvanceProyecto(this, true, listaTareas, listaColab, listaProyectos);
        win.setTitle("Avance de Proyectos");
        win.setLocationRelativeTo(this);
        win.setVisible(true);
    }//GEN-LAST:event_btnEstadoProyectoActionPerformed

    private void itemColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemColabActionPerformed
        btnColabsActionPerformed(evt);
    }//GEN-LAST:event_itemColabActionPerformed

    private void itemGestionTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionTareasActionPerformed
       btnGestionTareasActionPerformed(evt);
    }//GEN-LAST:event_itemGestionTareasActionPerformed

    private void itemProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProyectosActionPerformed
        btnProyectosActionPerformed(evt);
    }//GEN-LAST:event_itemProyectosActionPerformed

    private void itemAvanceTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAvanceTareasActionPerformed
        btnEstadoTareaActionPerformed(evt);
    }//GEN-LAST:event_itemAvanceTareasActionPerformed

    private void itemEstadoProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstadoProyectosActionPerformed
        btnEstadoProyectoActionPerformed(evt);
    }//GEN-LAST:event_itemEstadoProyectosActionPerformed

    private void mnAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAcercadeActionPerformed

    }//GEN-LAST:event_mnAcercadeActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        DlgAcercaDe dlg = new DlgAcercaDe(this, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
    }//GEN-LAST:event_itemAcercaActionPerformed

    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("img/icon.png"));

        return retValue;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColabs;
    private javax.swing.JButton btnEstadoProyecto;
    private javax.swing.JButton btnEstadoTarea;
    private javax.swing.JButton btnGestionTareas;
    private javax.swing.JButton btnProyectos;
    private javax.swing.JButton btnPuestos;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemAvanceTareas;
    private javax.swing.JMenuItem itemColab;
    private javax.swing.JMenuItem itemEstadoProyectos;
    private javax.swing.JMenuItem itemGestionTareas;
    private javax.swing.JMenuItem itemProyectos;
    private javax.swing.JMenuItem itemPuestos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnAcercade;
    private javax.swing.JMenu mnModulos;
    // End of variables declaration//GEN-END:variables
}
